### ISSUE TITLE
ReferenceError: abort is not defined

### ISSUE THREAD

**Issue by thoutojo** [deepwn/deepMiner#1]
Open https://deepc.cc/demo.html in Firefox 52 ESR (WebAssembly disabled), and display 'ReferenceError: abort is not defined' in console. Code below:

```
Module.asmLibraryArg = {
    "abort": abort,
    "assert": assert,
    "enlargeMemory": enlargeMemory,
```

Can you fix it, please? Thanks :)

**Comment by evil7** [comment]
Thx for Ur feedback. the bug happened because a little mistake I made. feel sad and sorry...
Now, I patched it and retry in FF ver.56 with config `javascript.options.wasm; false` And it's maybe fixed.
And I find that forget add `Access-Control-Allow-Origin: *` to do CORS setting. checking because of Ur feedback. thx again.
U can run it with Ur FF 52 ESR with `WebAssembly disabled` now. it should work without `cryptonight.wasm` now :)
Check it out pls : <https://deepc.cc/demo.html>

**Comment by thoutojo** [comment]
It's ok now, nice job!

BTW, maybe you need to add

```
if (req.url.match(/\.js$/)) {
	res.setHeader('content-type', 'text/javascript');
}
```

to server.js, else 'XML Parsing Error: syntax error Location: https://deepc.cc/lib/cryptonight-asmjs.min.js' will display in console (just show, don't interrupt the mining process).

In a word, thank you very much 👍

**Comment by evil7** [comment]
Will fix it next. Thanks for shared that. FF rules more hard than others. So sorry about I Can't have time testing on all the platform BCS my job in hospital for IT and others. Need working every day & night OMG... 😃 I'll rebuild it to better when have more and long rest.
So maybe rebuild all this with `express` to add control webUI and fix that bug for running with all kind of Fav browsers. (only CHR testing now)
THX AGAIN. nice done to ur join in dev.

**Comment by thoutojo** [comment]
Anytime :)
