### ISSUE TITLE
ERROR Unauthenticated 

### ISSUE THREAD

**Issue by vphelipe** [deepwn/deepMiner#12]
{"id":1512098314554,"jsonrpc":"2.0","error":{"code":-1,"message":"Unauthenticated"}}

This error is recurring, I reported this same problem to x25 code, the solution he used was this:

https://github.com/x25/coinhive-stratum-mining-proxy/commit/0a31eab2e421dc168f088fc09aa80ae7401f41c2

**Comment by vphelipe** [comment]
This script need fix handle multiple clients on same ip.

**Comment by vphelipe** [comment]
Debugging the code, I see that you are duplicating or sending more than one line in the variable data. Look:


ERROR: SyntaxError: Unexpected token { in JSON at position 75 - Data:{"id":1512101410305,"jsonrpc":"2.0","error":null,"result":{"status":"OK"}}
{"id":1512101410305,"jsonrpc":"2.0","error":null,"result":{"status":"OK"}}

ERROR: SyntaxError: Unexpected token { in JSON at position 253 - Data:{"jsonrpc":"2.0","method":"job","params":{"blob":"060681d882d105c180db4b6f2913fc66f3b51c006f090ccb6539b5f9a0944de192edfa3fd33cdb00000000ec7e260992a7bfa9d3c561e9fe8dca21b3924e8587312b43a680e6cde015e0c40c","job_id":"181972750394640","target":"ad9e1d02"}}
{"id":1512101455031,"jsonrpc":"2.0","error":null,"result":{"status":"OK"}}

ERROR: SyntaxError: Unexpected token { in JSON at position 75 - Data:{"id":1512101406934,"jsonrpc":"2.0","error":null,"result":{"status":"OK"}}
{"id":1512101406934,"jsonrpc":"2.0","error":null,"result":{"status":"OK"}}

ERROR: SyntaxError: Unexpected token { in JSON at position 75 - Data:{"id":1512101410318,"jsonrpc":"2.0","error":null,"result":{"status":"OK"}}
{"id":1512101410318,"jsonrpc":"2.0","error":null,"result":{"status":"OK"}}

ERROR: SyntaxError: Unexpected token { in JSON at position 75 - Data:{"id":1512101411110,"jsonrpc":"2.0","error":null,"result":{"status":"OK"}}
{"id":1512101411110,"jsonrpc":"2.0","error":null,"result":{"status":"OK"}}

**Comment by evil7** [comment]
OK I'll check it using in multiple. I thinking about this problem when red light on the way to my office.

And maybe this is WHY it happened:
The forked pid will use new connect to contact the pool .With another session maybe. So in fork's. `PoolSocket` will init to NOT sign in. Bcs that's pool server's session is working on `one session work` all `hash address` need login when it start in a new session (even U already have the miner's `workID` in `Father Process` pid. If session change to a `Sub Process` that an error come out with `null workID` bcs this). but in script. Here we are just follow the steps in `Father Process` and that why in `Sub` that making it doing the `step 2 get mined job` in a new session. Final that's why `Unauthenticated` come out (NO login with `Sub Process` but used `workID` just belong to `Father Process` the of pool "thinking" it is a error).

U can try fix it in local. I have a meeting at morning. And I'll debug it too when I get back to my office room.

* And for debug: U can `kill forever` OR `forever stopall` and go `/srv/deepMiner` use `node start` it log with output to `stdout`. Not need `cat log` any more.

make a debug & restart with command. that more EZ to dev.

**Comment by vphelipe** [comment]
I am debugging and I set to show only the errors, the main error is in the json parse of the variable data. And also the problem of error Unauthenticated.

Solving these 2 problems I believe will work just fine.

**Comment by evil7** [comment]
That's a problem in making the JSON jump from poolsocket to websocket. If wrong value show up that will make some var become `null` or `undefind` when trans to next step (to websocket). that will make an error in websocket. And a `big Error` here: the pool will ban your IP if to many same IP req (DDoS to ban) that's marked in hard-rule in `poolServer`. banned happened when I tested it fast when using just 10 threads. So I keep it running in single process this version and keep it minimum of pool connect.

Yeeep. that's why I'm not using in multiple at first. And I chose to working on dev webUI now because that. I'm keep testing how to handle sessions no banned efficiently work and more kind. thanks for your issue and maybe Ur ideas can final make it update. Let's hunting the bugs and maybe rebuild this proxy framework.

And... Are U a developer? or hacker / geeker? But that U have only sign up to github not long time and is that any other github's account U have? ;) Maybe U should join us.

* deepwn is just a little team by me and my friends. we are all geekers and hackers and developer working on `Net Security`. coding on some team tools or open some funny repo just for fun. :)

we used QQ for chatting but U also can context me in twitter: `@LJokerP (evil7)`

**Comment by vphelipe** [comment]
I'm a developer, but I'm not an expert haha. I'm interested in helping, yes. I was able to solve the JSON problem.

The variable data is getting more than one line a few times, I handled that and it's working fine now.

See if my solution is good for you:

> conn.pl.on('data', (data) => {
> 
>     var datee = data;
>     var lines = String(datee).split("\n");
> 
>     if (fields[1].length > 0) {
> 
>         pool2ws(lines[0]);
>         pool2ws(lines[1]);
> 
>         console.log('[SPLIT][0]=' + fields[0]);
>         console.log('[SPLIT][1]=' + fields[1]);
> 
> 
>     } else {
> 
>         pool2ws(data);
> 
>         console.log('NORMAL=' + data);
> 
>     }
> 
>     //console.log('[<] Response: ' + conn.uid + '\n\n' + data + '\n');
> });

**Comment by evil7** [comment]
Why not try use it? And why not let u show me more nice ideas? And...
Why not to check your email and click link :P
I'm outside have a meeting now. Can't have IDE to dev and testing. Glad if U in team dude.
create a dev branch to test. I think Ur ideas better than me in this JSON problem.

**Comment by vphelipe** [comment]
I'll try to help improve. I'll post my updates soon.
