### ISSUE TITLE
Pool settings for deepMiner?

### ISSUE THREAD

**Issue by freebet** [deepwn/deepMiner#50]
## Check list

- [ ] Ask for HELP.

- [x] Already check [README.md](https://github.com/deepwn/deepMiner/blob/master/README.md) but unsloved.

I install pool for solo mining, pool settings how should it be for deepMiner max performance?

especially difficulty?

thanks.

**Comment by evil7** [comment]
You can't let visitors on one website a long time like 24/7 of solo-miner, even a videos or movies site. if user finish visit and website be closed in browser the mining session will stop. so that's all good if follow this two rules.

1. keep in low difficult like 256 ~ 1000. (web hashrate <= 90hashs/Sec)
1. make it true never banned with your deepMiner server connecting IP.
