### ISSUE TITLE
Some NOT Q&A but check first pls

### ISSUE THREAD

**Issue by virgiltu** [deepwn/deepMiner#8]
Can anybody provide a good server service for this? 

Also a bit confused how to set this up on personal XMR Wallet. Any instructions would be helpful. 

Thank you for building this. Would be happy to donate if i can get it running on my sites.

**Comment by virgiltu** [comment]
ALso here are some option that would be nice to have, hash so we don’t run it in multiple tabs and throttle should be a must. 

Thanks again.

**Comment by evil7** [comment]
No one need donate but thanks for Ur "Star" Thx for you people like this.
I'll pay more time to dev this after my work over my jobs. Let's make this be a NICE project!~
This obj start just for fun. So there are NO documents or Q&A.
BUT many many many people open issue for `How To Use It`. So I'll talk about Ur question at here and Pin this for all install or settings Q&A.

## Install
1. U can just `./install.sh` OR `sh install.sh` to set it step by step.
1. If some config NOT clear. Please setting it by yourself. 

Wallert addr and some in `config.json` 
If domain unset at first check out the `deepMiner.js` last some line & `worker.js` at first some.
<https://github.com/deepwn/deepMiner/blob/web/deepMiner.js#L491>
<https://github.com/deepwn/deepMiner/blob/master/web/worker.js#L2>
U will see it `self.deepMiner.CONFIG` like this:
```javascript
self.deepMiner.CONFIG = {
    LIB_URL: "https://%deepMiner_domain%/lib/",
    WEBSOCKET_SHARDS: [["wss://%deepMiner_domain%/proxy"]],
    CAPTCHA_URL: "https://%deepMiner_domain%/captcha/",
    MINER_URL: "https://%deepMiner_domain%/media/miner.html"
};
```
if running `install.sh` it `%deepMiner_domain%` will be auto change to your input in.
But if NOT. Do change it by yourself that's OK.

If you don't need SSL support in you site. U can change `https / wss` to `http / ws`.
( SSL more good I think it is :P )

## API document
same like API in `coinhive.com` <https://coinhive.com/documentation/miner>
Chack `demo.html`. Some setting useful already in it. like threads 
## BUG found in running
1. Check the ports. is that server listening?
1. Check your setting. is `config.json` set done?
1. Check your domain & your servers. is ANY `iptables / settings / versions / lib support` are wrong?

**Comment by virgiltu** [comment]
Is there a way to use it without the pool? directly to the address.

**Comment by evil7** [comment]
U can build a pool to using by yourself OR use some others online. But U want mining U need a pool. Just like reason U want working money U need a job and a company to join in.

check this: <https://github.com/timekelp/xmr-pool-choice>

**Comment by razza-guhl** [comment]
Why doesn't happen anything on your demo-page? https://deepc.cc/demo.html

Sorry for this stupid question, but i don't get it... (Newbie Q&A)

**Comment by evil7** [comment]
This `pool.usxmrpool.com` is closing...
I fix this problem with change to another pool.
Use some other pool or build a pool by yourself. that's all good.
(I have changed it to `minexmr.pooldd.com:3333` now. U can rewrite to which pool u want to use)
check this: <https://github.com/timekelp/xmr-pool-choice>

**Comment by vphelipe** [comment]
Hello, this code works very well and I decided to create a pool to offer to everyone who uses this miner. The pool has been configured to have a low difficulty and thus have more shares, just as it is in the coinhive.

pool: pool.elitexmr.com
port: 8080

The difficulty is always 256 on port 8080

**Comment by evil7** [comment]
Wooo! that's good news. I'll change to yours now. Good job dude.

**Comment by evil7** [comment]
BUT there... Maybe just now working nice for one people who is master of pool.
Because I think maybe U should give a webGUI something to pay out XMR for user's miner? Or show some doc or status? Is that auto pay XMR? Maybe should have a page for user I think...
I means it maybe need a open API or web page for user used just like others pool.
I have change it to your pool now. And see the API is working great. But other users maybe need more function to using your pool and more Important they will need a `payback button` not like me just running in a demo page. Oops U must be forgot some. :P

**Comment by vphelipe** [comment]
The pool has automatic payments when the miner reaches 0.3 until the next block. It is a simple pool, but configured to work well with this code because of its low difficulty and non-banning in case of connections of many miners, as it happens in the vast majority of pools.

Enter your wallet number on the website and have your hashrate status and balance.

**Comment by evil7** [comment]
OK. I put this pool-info into README.md
